repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(.+)(?<!\_version)\.py$
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(.+)(?<!\_version)\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.8.0
          - pyflakes==2.4.0
          - pydocstyle==6.1.1
          - flake8-comprehensions==3.8.0
          - flake8-noqa==1.2.1
          - mccabe==0.6.1
        files: ^(.+)(?<!\_version)\.py$
  - repo: local
    hooks:
      - id: q2lint
        name: q2lint
        language: python
        pass_filenames: false
        entry: q2lint
        stages: [ commit ]
        additional_dependencies:
          - https://github.com/qiime2/q2lint/archive/master.zip
