package:
  name: q2-assembly
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - quast
  - beautifulsoup4
  - biopython
  - bowtie2 {{ bowtie2 }}
  - gridss
  - insilicoseq
  - mason
  - megahit {{ megahit }}
  - pysam {{ pysam }}
  - qiime2 >={{ qiime2 }}
  - q2-fondue >={{ q2_fondue }}
  - q2-types >={{ q2_types }}
  - q2templates >={{ q2templates }}
  - q2-demux >={{ q2_demux }}
  - samtools
  - shortuuid
  - spades {{ spades }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - parameterized
  - pytest-xdist
  imports:
  - q2_assembly
  - qiime2.plugins.assembly
  commands:
  - pytest --pyargs q2_assembly -n 4
about:
  home: https://github.com/bokulich-lab/q2-assembly
  license: BSD-3-Clause
  license_family: BSD
