{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-assembly
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    # TODO: add quast here once it works on python 3.8
    - beautifulsoup4
    - biopython <=1.78
    - bowtie2 ==2.4.4
    - insilicoseq
    - megahit ==1.2.9
    - qiime2 {{ release }}.*
    - q2-types-genomics {{ release }}.*
    - q2templates {{ release }}.*
    - samtools
    - spades ==3.15.2

test:
  imports:
    - q2_assembly
    - qiime2.plugins.assembly

about:
  home: https://github.com/bokulich-lab/q2-assembly
  license: BSD-3-Clause
  license_family: BSD
