{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-assembly
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - quast
    - beautifulsoup4
    - biopython <=1.78
    - bowtie2 {{ bowtie2 }}
    - gridss
    - insilicoseq
    - megahit ==1.2.9
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types-genomics {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - samtools
    - spades ==3.15.2

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - q2_assembly
    - qiime2.plugins.assembly
  commands:
    - pytest --cov q2_assembly --cov-report xml:coverage.xml --pyargs q2_assembly

about:
  home: https://github.com/bokulich-lab/q2-assembly
  license: BSD-3-Clause
  license_family: BSD
